# Generated by Django 6.0 on 2026-02-02 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('CEO', models.CharField(max_length=100)),
                ('est_year', models.IntegerField()),
                ('origin', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prod_name', models.CharField(max_length=100)),
                ('colors', models.CharField(max_length=10)),
                ('price', models.FloatField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('cc', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='cbvapp.company')),
            ],
        ),
    ]
