# Generated by Django 6.0 on 2026-02-02 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbvapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='colors',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='mileage',
            new_name='miliege',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='Prod_name',
            new_name='product_name',
        ),
    ]
